services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db

  redis:
    image: redis:8.8-m03-trixie
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio-dev
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: minio-dev-password
    volumes:
      - minio_dev_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-dev
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-dev
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./otel/otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro

volumes:
  mongo_dev_data:
  redis_dev_data:
  minio_dev_data:
